import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Footer } from "../components/Footer";
import { Links } from "../components/Links";
import { HeadLine } from "../components/Headline";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeadLine
          page="about"
          number={1111}
          array={[1, 2, 3]}
          obj={{ foo: "foo", bar: "bar" }}
          boolean
          code={<code className={styles.code}>pages/about.js</code>}
        />
        <Links />
      </main>

      <Footer styles={styles} Image={Image}></Footer>
    </div>
  );
}
